import merchant1 from '../assets/Merchants/Merchant-1.jpg';
import { StarIcon } from '@heroicons/react/24/solid'
const ServiceProviders = [
    {
        id: 1,
        firstName: 'John',
        lastName: 'Doe',
        name: 'PlumbPro Services',
        service: 'Plumbing',
        rating: 4.5,
        location: 'Lagos',
        phone: '08012345678',
        email: 'john.doe@plumbpro.com',
        availability: 'Available 7 days a week',    
        rate: 'R500 per hour',
        image: merchant1,
        icon: StarIcon,
    },
    {
        id: 2,
        firstName: 'Jane',
        lastName: 'Smith',
        name: 'ElectroFix Solutions',
        service: 'Electrical',
        rating: 4.7,
        location: 'Cape Town',
        phone: '08087654321',
        email: 'jane.smith@electrofix.com',
        availability: 'Available weekdays',
        rate: 'R600 per hour',
        image: merchant1,
        icon: StarIcon,
    },
    {
        id: 3,
        firstName: 'Michael',
        lastName: 'Johnson',
        name: 'Carpentry Masters',
        service: 'Carpentry',
        rating: 4.8,
        location: 'Johannesburg',
        phone: '08011223344',
        email: 'michael.johnson@carpentrymasters.com',
        availability: 'Available weekends',
        rate: 'R550 per hour',
        image: merchant1,
        icon: StarIcon,
    },
    {
        id: 4,
        firstName: 'Emily',
        lastName: 'Davis',
        name: 'CleanSweep Services',
        service: 'Cleaning',
        rating: 4.6,
        location: 'Durban',
        phone: '08099887766',
        email: 'emily.davis@cleansweep.com',
        availability: 'Available 7 days a week',
        rate: 'R300 per hour',
        image: merchant1,
        icon: StarIcon,
    },
    {
        id: 5,
        firstName: 'David',
        lastName: 'Wilson',
        name: 'PaintPerfect',
        service: 'Painting',
        rating: 4.9,
        location: 'Pretoria',
        phone: '08022334455',
        email: 'david.wilson@paintperfect.com',
        availability: 'Available weekdays',
        rate: 'R450 per hour',
        image: merchant1,
        icon: StarIcon,
    },
    {
        id: 6,
        firstName: 'Sarah',
        lastName: 'Brown',
        name: 'GreenThumb Gardening',
        service: 'Gardening',
        rating: 4.4,
        location: 'Port Elizabeth',
        phone: '08033445566',
        email: 'sarah.brown@greenthumb.com',
        availability: 'Available weekends',
        rate: 'R350 per hour',
        image: merchant1,
        icon: StarIcon,
    },
    {
        id: 7,
        firstName: 'James',
        lastName: 'Taylor',
        name: 'Roofing Experts',
        service: 'Roofing',
        rating: 4.7,
        location: 'Bloemfontein',
        phone: '08044556677',
        email: 'james.taylor@roofingexperts.com',
        availability: 'Available 7 days a week',
        rate: 'R700 per hour',
        image: merchant1,
        icon: StarIcon,
    },
    {
        id: 8,
        firstName: 'Olivia',
        lastName: 'Anderson',
        name: 'Landscape Pros',
        service: 'Landscaping',
        rating: 4.8,
        location: 'East London',
        phone: '08055667788',
        email: 'olivia.anderson@landscapepros.com',
        availability: 'Available weekdays',
        rate: 'R500 per hour',
        image: merchant1,
        icon: StarIcon,
    },
    {
        id: 9,
        firstName: 'Daniel',
        lastName: 'Thomas',
        name: 'PestControl Experts',
        service: 'Pest Control',
        rating: 4.6,
        location: 'Kimberley',
        phone: '08066778899',
        email: 'daniel.thomas@pestcontrol.com',
        availability: 'Available weekends',
        rate: 'R400 per hour',
        image: merchant1,
        icon: StarIcon,
    },
    {
        id: 10,
        firstName: 'Sophia',
        lastName: 'Martinez',
        name: 'MoveIt Services',
        service: 'Moving Services',
        rating: 4.9,
        location: 'Polokwane',
        phone: '08077889900',
        email: 'sophia.martinez@moveit.com',
        availability: 'Available 7 days a week',
        rate: 'R650 per hour',
        image: merchant1,
        icon: StarIcon,
    }
];

export default ServiceProviders;
